language.Add("showhidden.title", "PlayerClips & ShowTriggers menu")
language.Add("showhidden.count", "Count: ")
language.Add("showhidden.reset", "Reset")
language.Add("showhidden.material_tooltip", "Material: %s\nColor: %s")
language.Add("showhidden.mat.0", "Wireframe")
language.Add("showhidden.mat.1", "Default")
language.Add("showhidden.mat.2", "Solid color")

language.Add("showclips.msg.lags", "Reading information from map file.... There may be some lags!")
language.Add("showclips.msg.enabled", "Player clips are enabled. Use !clipsmenu to configure")
language.Add("showclips.msg.disabled", "Player clips are now disabled!")
language.Add("showclips.msg.error", "Can't read information from the map .bsp file (see error message in console ~)")
language.Add("showclips.gui.enable", "Draw player-clip brushes")
language.Add("showclips", "Player clip brushes")

language.Add("showclips.type.1", "Player clip brushes")
language.Add("showclips.type.2", "Invisible wall brushes")
language.Add("showclips.type.3", "Invisible ladders")
language.Add("showclips.type.4", "NoDraw brushes")
language.Add("showclips.type.5", "SkyBox brushes")

language.Add("showclips.props", "Static props collision models")
language.Add("showclips.props.enabled", "Static props collision models are enabled.")
language.Add("showclips.props.disabled", "Static props collision models are now disabled!")

language.Add("showtriggers.msg.enabled", "Triggers are enabled. Use !triggersmenu to configure")
language.Add("showtriggers.msg.disabled", "Triggers are now disabled!")
language.Add("showtriggers.gui.enable", "Show trigger brushes")

language.Add("showtriggers.type.1", "Other triggers...")
language.Add("showtriggers.type.2", "Teleports (reset)")
language.Add("showtriggers.type.3", "Teleports with filter")
language.Add("showtriggers.type.4", "Boosters: push")
language.Add("showtriggers.type.5", "Boosters: base-velocity")
language.Add("showtriggers.type.6", "Boosters: gravity")
language.Add("showtriggers.type.7", "PreSpeed prevention")
language.Add("showtriggers.type.8", "BunnyHop platforms")
